#!/usr/bin/env tsx
/**
 * HUNGERNADS - $HNADS Token Launch Script
 *
 * Launches the $HNADS token on nad.fun using the NadFunClient.
 * Reads credentials from .env (MONAD_RPC_URL, PRIVATE_KEY).
 * Appends the resulting NADFUN_TOKEN_ADDRESS to .env on success.
 *
 * Prerequisites:
 *   1. Place your logo at assets/hnads-logo.png
 *   2. Ensure .env has MONAD_RPC_URL and PRIVATE_KEY
 *
 * Usage:
 *   npx tsx scripts/launch-token.ts
 *   npm run launch-token
 *
 * "May the nads be ever in your favor."
 */

import 'dotenv/config';

import * as fs from 'node:fs';
import * as path from 'node:path';
import { NadFunClient, parseEther, type CreateTokenResult } from '../src/chain/nadfun';

// ─── Constants ──────────────────────────────────────────────────────────────

const TOKEN_NAME = 'HungerNads';
const TOKEN_SYMBOL = 'HNADS';
const TOKEN_DESCRIPTION =
  'AI gladiator colosseum on Monad. 5 AI agents fight to survive. ' +
  'Nads bet, sponsor, and watch. Agents learn, evolve, and die. ' +
  'Last nad standing wins. May the nads be ever in your favor.';
const TOKEN_WEBSITE = 'https://hungernads.xyz';
const TOKEN_TWITTER = 'https://x.com/hungernads';

const INITIAL_BUY_AMOUNT = parseEther('0.1'); // 0.1 MON

const LOGO_PATH = path.resolve(__dirname, '..', 'assets', 'hnads-logo.png');
const ENV_PATH = path.resolve(__dirname, '..', '.env');

// ─── Validation ─────────────────────────────────────────────────────────────

function validateEnvironment(): void {
  const missing: string[] = [];

  if (!process.env.MONAD_RPC_URL) missing.push('MONAD_RPC_URL');
  if (!process.env.PRIVATE_KEY) missing.push('PRIVATE_KEY');

  if (missing.length > 0) {
    console.error(`[launch] Missing required env vars: ${missing.join(', ')}`);
    console.error('[launch] Ensure your .env file is configured. See .env.example.');
    process.exit(1);
  }

  if (!fs.existsSync(LOGO_PATH)) {
    console.error(`[launch] Logo file not found: ${LOGO_PATH}`);
    console.error('[launch] Place your token logo PNG at assets/hnads-logo.png before launching.');
    process.exit(1);
  }
}

// ─── .env Writer ────────────────────────────────────────────────────────────

function appendToEnv(key: string, value: string): void {
  const line = `\n# NadFun Token (auto-generated by launch-token.ts)\n${key}=${value}\n`;

  if (fs.existsSync(ENV_PATH)) {
    const existing = fs.readFileSync(ENV_PATH, 'utf-8');
    if (existing.includes(`${key}=`)) {
      // Replace existing value
      const updated = existing.replace(
        new RegExp(`^${key}=.*$`, 'm'),
        `${key}=${value}`,
      );
      fs.writeFileSync(ENV_PATH, updated, 'utf-8');
      console.log(`[launch] Updated ${key} in .env`);
    } else {
      fs.appendFileSync(ENV_PATH, line, 'utf-8');
      console.log(`[launch] Appended ${key} to .env`);
    }
  } else {
    fs.writeFileSync(ENV_PATH, line.trim() + '\n', 'utf-8');
    console.log(`[launch] Created .env with ${key}`);
  }
}

// ─── Main ───────────────────────────────────────────────────────────────────

async function launchToken(): Promise<void> {
  console.log('');
  console.log('  ╔═══════════════════════════════════════════════╗');
  console.log('  ║   $HNADS TOKEN LAUNCH - nad.fun (testnet)    ║');
  console.log('  ╚═══════════════════════════════════════════════╝');
  console.log('');

  // Validate
  validateEnvironment();

  // Read logo image
  const imageBuffer = fs.readFileSync(LOGO_PATH);
  const imageBlob = new Blob([imageBuffer], { type: 'image/png' });
  console.log(`[launch] Logo loaded: ${LOGO_PATH} (${(imageBuffer.length / 1024).toFixed(1)} KB)`);

  // Create client
  const client = new NadFunClient({
    rpcUrl: process.env.MONAD_RPC_URL!,
    privateKey: process.env.PRIVATE_KEY as `0x${string}`,
    network: 'testnet',
  });

  console.log(`[launch] Wallet: ${client.walletAddress}`);
  console.log(`[launch] Network: testnet`);
  console.log('');
  console.log(`[launch] Token: ${TOKEN_NAME} ($${TOKEN_SYMBOL})`);
  console.log(`[launch] Initial buy: 0.1 MON`);
  console.log(`[launch] Website: ${TOKEN_WEBSITE}`);
  console.log(`[launch] Twitter: ${TOKEN_TWITTER}`);
  console.log('');
  console.log('[launch] Creating token on nad.fun...');
  console.log('');

  let result: CreateTokenResult;
  try {
    result = await client.createHNADS({
      name: TOKEN_NAME,
      symbol: TOKEN_SYMBOL,
      description: TOKEN_DESCRIPTION,
      image: imageBlob,
      imageContentType: 'image/png',
      website: TOKEN_WEBSITE,
      twitter: TOKEN_TWITTER,
      initialBuyAmount: INITIAL_BUY_AMOUNT,
    });
  } catch (err) {
    console.error('[launch] Token creation failed:', err);
    process.exit(1);
  }

  // Log results
  console.log('');
  console.log('  ╔═══════════════════════════════════════════════╗');
  console.log('  ║          TOKEN CREATED SUCCESSFULLY           ║');
  console.log('  ╚═══════════════════════════════════════════════╝');
  console.log('');
  console.log(`  Token Address:  ${result.tokenAddress}`);
  console.log(`  Pool Address:   ${result.poolAddress}`);
  console.log(`  Transaction:    ${result.transactionHash}`);
  console.log(`  Image URI:      ${result.imageUri}`);
  console.log(`  Metadata URI:   ${result.metadataUri}`);
  console.log(`  NSFW:           ${result.isNsfw}`);
  console.log('');

  // Save to .env
  appendToEnv('NADFUN_TOKEN_ADDRESS', result.tokenAddress);
  appendToEnv('NADFUN_POOL_ADDRESS', result.poolAddress);

  console.log('');
  console.log('  "May the nads be ever in your favor."');
  console.log('');
}

// ─── Run ────────────────────────────────────────────────────────────────────

launchToken().catch((err) => {
  console.error('\nFATAL ERROR:', err);
  process.exit(1);
});
